---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: mydiplom
  name: mydiplom
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: http
      nodePort: 30880
  selector:
    app: mydiplom
  type: NodePort
