---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydiplom
    name: mydiplom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydiplom    
  template:
    metadata:
      labels:
        app: mydiplom        
    spec:
      containers:
        - image: "{{ .Values.image_frontend.repository }}:{{ .Values.image_frontend.tag | default .Values.image.tag }}"
          name: frontend
          ports:
            - containerPort: 80
              name: http
      restartPolicy: Always